Updated a Typo in Point - 8
hasnainmakada-99/Open-Source-With-Hasnain pull request #100
Opened 2023-02-04 14:57 UTC by Akash3121

updated a typo in line no: 13, point 8

```diff
-thay
+they
```

@hasnainmakada-99 please look into it. 
Thank you!!

# 🛠️ Fixes issue #
# 📇 Changes proposed 
# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the documentation
- [ ] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-02-04 15:07 UTC, hasnainmakada-99 requested changes

2023-02-04 15:07 UTC, hasnainmakada-99 commented on pages/android-development-resources.md
> +| **8. Now they you've learned let's build it Project 1**| <center> [![colab](https://i.ytimg.com/vi/KLuiX1oHBII/mqdefault.jpg "colab")](https://www.youtube.com/playlist?list=PL7NYbSE8uaBCMVBVg6cskGz
change it from `they` to `that`

2023-02-05 05:56 UTC, hasnainmakada-99 commented
A similar PR has been raised for the same issue, Please check out the PR's tab

2023-02-05 05:56 UTC, closed without merging

2023-02-05 14:31 UTC, Akash3121 commented
sorry my mistake, I didn't check the PR's tab.
Thanks for closing!