Update react-resources.md
hasnainmakada-99/Open-Source-With-Hasnain pull request #186
Opened 2023-10-05 16:27 UTC by AdebayoIbrahim

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Updated react-resources.md to fit beginners guide

2023-10-10 02:41 UTC, hasnainmakada-99 requested changes
Please look onto the requested changes @AdebayoIbrahim

2023-10-10 02:41 UTC, hasnainmakada-99 commented on pages/react-resources.md
> +| 7. Learn React Basics | [![Web Development](https://i.ibb.co/pbf14TL/w3-pull-res.png "WebDevelopment")](https://www.w3schools.com/react)| [Here you go](https://www.w3schools.com/react)
Fix the numbering here @AdebayoIbrahim

2023-10-11 08:54 UTC, AdebayoIbrahim commented
> Please look onto the requested changes @AdebayoIbrahim 

Done boss 🙌

2023-10-12 03:21 UTC, hasnainmakada-99 approved these changes
LGTM @AdebayoIbrahim

2023-10-12 03:21 UTC, merged

2023-10-12 03:22 UTC, hasnainmakada-99 commented
@all-contributors please add @AdebayoIbrahim as a contributor of content

2023-10-12 03:23 UTC, hasnainmakada-99 commented
@AdebayoIbrahim I am adding you as a contributor to the OSWH project as you have provided a lot of useful resources to the community, once again thanks for all of your contributions

2023-10-12 12:29 UTC, AdebayoIbrahim commented
> @AdebayoIbrahim I am adding you as a contributor to the OSWH project as you have provided a lot of useful resources to the community, once again thanks for all of your contributions

@hasnainmakada-99  Wow Thanks I am delighted to hear that Boss